version: '3.7'

services:
  app:
    container_name: cdac_tracking-app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:3000
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - common
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379  # we'll use internal port
  redis:
    image: redis:5.0.7-buster
    hostname: ${REDIS_HOST}
    container_name: cdac_tracking-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - common
    volumes:
      - redis-db:/data
networks:
  common:
    name: cdac_tracking_network
    driver: bridge
volumes:
  redis-db:
  postgres-db: