version: '3.7'

services:
  app:
    container_name: cdac_tracking-app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:3000
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - cdac_tracking
  redis:
    image: redis:5.0.7-buster
    container_name: cdac_tracking-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - cdac_tracking
    volumes:
    - redis-db:/var/lib/redis
networks:
  cdac_tracking:
volumes:
  redis-db: