version: '3.7'

services:
  psql:
    ports:
      - ${POSTGRES_PORT}:5432
    image: postgres:latest
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: cdac_tracking-hasura_psql
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - common

  graphql-engine:
    hostname: ${HASURA_HOST}
    image: hasura/graphql-engine:v2.10.0
    ports:
      - ${HASURA_PORT}:${HASURA_PORT}
    depends_on:
      - psql
    restart: always
    container_name: cdac_tracking-hasura_graphql_engine
    networks:
      - common
    env_file:
      - ../.env
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@cdac_tracking-hasura_psql:5432/${POSTGRES_DB}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false # disabled; use `hasura console instead`
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - HASURA_GRAPHQL_SERVER_PORT=${HASURA_PORT}
networks:
  common:
    name: cdac_tracking_network
    driver: bridge
volumes:
  redis-db:
  postgres-db: